class Test_data:
    response_lastCandles = {'id': 10, 't': 0, 'data': [{'close': 197.1, 'high': 197.23, 'open': 196.58,
                                 'datetime': {'week_day': 1, 'hour': 23, 'min': 50, 'day': 4, 'month': 5, 'count': 1,
                                              'sec': 0, 'ms': 0, 'year': 2020}, 'volume': 81629, 'interval': 10,
                                 'sec': 'SBER', 'low': 196.53, 'class': 'QJSIM'},
                                {'close': 196.83, 'high': 197.3, 'open': 197.17,
                                 'datetime': {'week_day': 2, 'hour': 0, 'min': 0, 'day': 5, 'month': 5, 'count': 1,
                                              'sec': 0, 'ms': 0, 'year': 2020}, 'volume': 57512, 'interval': 10,
                                 'sec': 'SBER', 'low': 196.83, 'class': 'QJSIM'},
                                {'close': 197.05, 'high': 197.05, 'open': 196.83,
                                 'datetime': {'week_day': 2, 'hour': 0, 'min': 10, 'day': 5, 'month': 5, 'count': 1,
                                              'sec': 0, 'ms': 0, 'year': 2020}, 'volume': 18915, 'interval': 10,
                                 'sec': 'SBER', 'low': 196.58, 'class': 'QJSIM'},
                                {'close': 196.98, 'high': 197.05, 'open': 197.05,
                                 'datetime': {'week_day': 2, 'hour': 0, 'min': 20, 'day': 5, 'month': 5, 'count': 1,
                                              'sec': 0, 'ms': 0, 'year': 2020}, 'volume': 13243, 'interval': 10,
                                 'sec': 'SBER', 'low': 196.77, 'class': 'QJSIM'},
                                {'close': 196.99, 'high': 197.12, 'open': 196.93,
                                 'datetime': {'week_day': 2, 'hour': 0, 'min': 30, 'day': 5, 'month': 5, 'count': 1,
                                              'sec': 0, 'ms': 0, 'year': 2020}, 'volume': 45139, 'interval': 10,
                                 'sec': 'SBER', 'low': 196.82, 'class': 'QJSIM'},
                                {'close': 196.78, 'high': 197.02, 'open': 196.99,
                                 'datetime': {'week_day': 2, 'hour': 0, 'min': 40, 'day': 5, 'month': 5, 'count': 1,
                                              'sec': 0, 'ms': 0, 'year': 2020}, 'volume': 28205, 'interval': 10,
                                 'sec': 'SBER', 'low': 196.78, 'class': 'QJSIM'},
                                {'close': 196.49, 'high': 196.78, 'open': 196.78,
                                 'datetime': {'week_day': 2, 'hour': 0, 'min': 50, 'day': 5, 'month': 5, 'count': 1,
                                              'sec': 0, 'ms': 0, 'year': 2020}, 'volume': 26563, 'interval': 10,
                                 'sec': 'SBER', 'low': 196.26, 'class': 'QJSIM'},
                                {'close': 196.52, 'high': 196.52, 'open': 196.49,
                                 'datetime': {'week_day': 2, 'hour': 1, 'min': 0, 'day': 5, 'month': 5, 'count': 1,
                                              'sec': 0, 'ms': 0, 'year': 2020}, 'volume': 55659, 'interval': 10,
                                 'sec': 'SBER', 'low': 196.2, 'class': 'QJSIM'},
                                {'close': 196.35, 'high': 196.55, 'open': 196.52,
                                 'datetime': {'week_day': 2, 'hour': 1, 'min': 10, 'day': 5, 'month': 5, 'count': 1,
                                              'sec': 0, 'ms': 0, 'year': 2020}, 'volume': 28685, 'interval': 10,
                                 'sec': 'SBER', 'low': 196.2, 'class': 'QJSIM'}], 'cmd': 'get_candles_from_data_source'}